/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package swimming_pool;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Person p = new Person(25, false, false);
        PersonalTicket t = new PersonalTicket(p, 2, 600);
    }
}
